Queremos una matriz de estudiantes y notas:

$$\begin{bmatrix}  & Asignatura 1 & Asignatura 2 & ...\\ Alumno 1 & 7 & 8 & ...\\ Alumno 2 & 8 & 6 & ...\\ ... & ... & ... & ... \end{bmatrix}$$

In [1]:
# Creamos la matriz

In [3]:
numero_courses = int(input("Introduzca número de clases: "))
courses = [] # Inicializamos lista vacía de courses

for i in range(numero_courses):
    name = input("Introduzca el nombre de la clase: ")
    courses.append(name)

Introduzca número de clases: 2
Introduzca el nombre de la clase: Física
Introduzca el nombre de la clase: Calculo


In [4]:
courses

['Física', 'Calculo']

In [5]:
numero_alumnos = int(input("Introduzca número de alumnos: "))
alumnos = [] # Inicializamos lista vacía de courses

for i in range(numero_alumnos):
    name = input("Introduzca el nombre del alumno: ") 
    alumnos.append(name)

Introduzca número de alumnos: 3
Introduzca el nombre del alumno: María
Introduzca el nombre del alumno: Pedro
Introduzca el nombre del alumno: Cris


In [6]:
alumnos

['María', 'Pedro', 'Cris']

In [9]:
# Crear matriz de notas vacía
# Recorrer alumnos
    # Para cada alumno recorro todas las asignaturas
        # Pedimos nota
        # Añado nota de asignatura

In [12]:
numero_courses

2

In [13]:
grades = [  [3,5,7]   , [6,8,9], [3,8,9] ]

In [14]:
grades[0]

[3, 5, 7]

In [ ]:
grades = [  [3], [5], [7] ...]

In [63]:
grades = []
for i in range(numero_alumnos):
    print("Alumno: {0}: ".format( alumnos[i] ))
    
    notas_alumno = []
    for j in range(numero_courses):
        nota = float(input("Nota de {0}: ".format( courses[j] )))
        notas_alumno.append(nota)
        
    grades.append(notas_alumno)

Alumno: María: 
Nota de Física: 1
Nota de Calculo: 2
Alumno: Pedro: 
Nota de Física: 3
Nota de Calculo: 4
Alumno: Cris: 
Nota de Física: 5
Nota de Calculo: 6


In [ ]:
grades[i][j] = nota

In [26]:
grades

[[7.0, 8.0], [5.0, 6.0], [8.0, 4.0]]

In [20]:
import numpy as np
np.array(grades)

array([[7., 8.],
       [5., 6.],
       [8., 4.]])

In [25]:
grades[2][0] 

8.0

In [53]:
grades  = [[0,0]] * numero_alumnos

In [54]:
grades

[[0, 0], [0, 0], [0, 0]]

In [55]:
grades[1][0]

0

In [56]:
grades

[[0, 0], [0, 0], [0, 0]]

In [ ]:
grades[i][j] = nota

In [57]:
grades = [[0,0]] * numero_alumnos
for i in range(numero_alumnos):
    print("Alumno: {0}: ".format( alumnos[i] ))
    
    for j in range(numero_courses):
        nota = float(input("Nota de {0}: ".format( courses[j] )))
        grades[i][j] = nota

Alumno: María: 
Nota de Física: 1
Nota de Calculo: 2
Alumno: Pedro: 
Nota de Física: 3
Nota de Calculo: 4
Alumno: Cris: 
Nota de Física: 5
Nota de Calculo: 6


In [58]:
grades

[[5.0, 6.0], [5.0, 6.0], [5.0, 6.0]]

In [61]:
grades[0][1] = 2

In [62]:
grades

[[5.0, 2], [5.0, 2], [5.0, 2]]

Nuevo grades

In [64]:
grades

[[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]]

Media alumnos

In [66]:
grades_numpy = np.array(grades)
grades_numpy

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [67]:
medias = grades_numpy.mean(1) # Con un 1 nos hace la media de cada fila (alumno)
medias

array([1.5, 3.5, 5.5])

In [68]:
alumnos

['María', 'Pedro', 'Cris']

In [69]:
nombre = input("Introduca nombre del alumno: ")
indice = alumnos.index(nombre) # Ver ejemplo de la celda anterior para entender esta línea
media_alumno = medias[indice]
    
print("Media de {0} es: {1}".format(nombre, media_alumno))

Introduca nombre del alumno: María
Media de María es: 1.5


Media asignaturas

In [70]:
# Para poder aplicar la función mean, es necesario que la matriz sea una matriz numpy. 
# Por si acaso, la transformo a np.array 
grades_numpy = np.array(grades)
medias = grades_numpy.mean(0) # Con un 0 nos hace la media de cada columna (asignatura)
medias

array([3., 4.])

In [71]:
nombre = input("Introduca nombre de la asignatura: ")
indice = courses.index(nombre) # Ver ejemplo de la celda anterior para entender esta línea
media_asignatura = medias[indice]
    
print("Media de {0} es: {1}".format(nombre, media_asignatura))
    

Introduca nombre de la asignatura: Calculo
Media de Calculo es: 4.0


In [72]:
alumnos

['María', 'Pedro', 'Cris']

In [86]:
primera_linea = "\t" + "\t".join(courses)
print(primera_linea) # Hay maneras más elegantes de hacer esto pero no hace falta romperse la cabeza
#print("\t" +  courses[0]+ "\t"+courses[1])
for i in range(numero_alumnos):        
    alumno = alumnos[i]
    string_notas = ""
    for j in range(numero_courses):
        nota = str(grades[i][j])
        string_notas = string_notas + "\t"+ nota # Añadimos el espacio (\t) y la nota extraida
    linea = alumno + string_notas # Construimos la línea
    print(linea)

	Física	Calculo
María	1.0	2.0
Pedro	3.0	4.0
Cris	5.0	6.0


In [75]:
courses

['Física', 'Calculo']

In [83]:
"\t".join(courses)

'Física\tCalculo'

In [84]:
"\t"+"\t".join(courses)

'\tFísica\tCalculo'

In [85]:
print("\t"+"\t".join(courses))

	Física	Calculo


In [88]:
datos_al1 = {'R': 5.0, 'Python': 6.0, 'Física': 7.0}
datos_al2 = {'R': 3.0, 'Python': 7.0, 'Física': 8.0}

In [97]:
nombres_alumnos = ["María", "Pedro"]
datos_alumnos  = [datos_al1, datos_al2]

In [98]:
datos_alumnos[0]["R"]

5.0

In [99]:
nombres_alumnos[0]

'María'

In [101]:
datos_alumnos = {'María': {'R': 5.0, 'Python': 6.0, 'Física': 7.0},
                 'Pedro': {'R': 7.0, 'Python': 8.0, 'Física': 9.0}}

In [102]:
datos_alumnos["María"]["R"]

5.0

In [104]:
notas_nico = [1,2,3]

In [105]:
datos_alumnos = {'María': [5.0, 6.0, 7.0],
                 'Pedro': [7.0, 8.0, 9.0],
                'Nico':notas_nico}

In [106]:
datos_alumnos

{'María': [5.0, 6.0, 7.0], 'Pedro': [7.0, 8.0, 9.0], 'Nico': [1, 2, 3]}

In [107]:
datos_alumnos = {'María': {'R': 5.0, 'Python': 6.0, 'Física': 7.0},
                 'Pedro': {'R': 7.0, 'Python': 8.0, 'Física': 9.0}}

In [109]:
clase = input("Introduca asignatura: ")

Introduca asignatura: R


In [110]:


suma_notas = 0 # Para acumular las notas de todos
num_alumnos = 0
for clave, valor in datos_alumnos.items():
    
    suma_notas = suma_notas + valor[clase]
    
    

KeyError: 0