# Program 1 - Primero hecho con listas

Queremos una matriz de estudiantes y notas:

$$\begin{bmatrix}  & Asignatura 1 & Asignatura 2 & ...\\ Alumno 1 & 7 & 8 & ...\\ Alumno 2 & 8 & 6 & ...\\ ... & ... & ... & ... \end{bmatrix}$$

Primero creamos las listas de alumnos y asignaturas

In [4]:
numero_asignaturas = int(input("Introduzca el número de clases: "))
numero_alumnos = int(input("Introduzca el número de alumnos: "))

Introduzca el número de clases: 3
Introduzca el número de alumnos: 4


In [5]:
alumnos = []
for i in range(numero_alumnos):
    alumno = input("Introduzca el nombres del alumno: ")
    alumnos.append(alumno)

Introduzca el nombres del alumno: Pedro
Introduzca el nombres del alumno: Felipe
Introduzca el nombres del alumno: Maria
Introduzca el nombres del alumno: Cris


In [7]:
asignaturas = []
for i in range(numero_asignaturas):
    asignatura = input("Introduzca el nombre de asignatura: ")
    asignaturas.append(asignatura)

Introduzca el nombre de asignatura: R
Introduzca el nombre de asignatura: Python
Introduzca el nombre de asignatura: Contabilidad


Otra manera, con funciones

In [6]:
def rellenarLista(lista_a_rellenar, numero_componentes):
    for i in range(numero_componentes):
        valor = input("Introduzca el siguiente componente: ")
        lista_a_rellenar.append(valor)
    

In [8]:
alumnos = []
rellenarLista(alumnos, 4)

Introduzca el siguiente componente: Pedro
Introduzca el siguiente componente: Felipe
Introduzca el siguiente componente: Maria
Introduzca el siguiente componente: Cris


Ahora creamos la lista de notas

In [38]:
notas = []
for fila in range(numero_alumnos):
    notas.append([0]*numero_asignaturas)
    print("\nAlumno: {0}".format(alumnos[fila]))
    for columna in range(numero_asignaturas):
        nota = float(input("Asignatura {0}: ".format(asignaturas[columna])))
        notas[fila][columna] = nota


Alumno: Pedro
Asignatura R: 6
Asignatura Python: 7
Asignatura Contabilidad: 8

Alumno: Felipe
Asignatura R: 6
Asignatura Python: 5
Asignatura Contabilidad: 6

Alumno: Maria
Asignatura R: 7
Asignatura Python: 9
Asignatura Contabilidad: 9

Alumno: Cris
Asignatura R: 8
Asignatura Python: 7
Asignatura Contabilidad: 6


In [39]:
notas

[[6.0, 7.0, 8.0], [6.0, 5.0, 6.0], [7.0, 9.0, 9.0], [8.0, 7.0, 6.0]]

#### Explicación de `notas.append([0]*numero_asignaturas)`

In [24]:
lista_aux

[0, 0, 0]

In [20]:
lista_aux[2] = 4

In [21]:
lista_aux

[0, 0, 4]

In [25]:
matrix_aux = []

In [ ]:
primer_elemento = [0] * 3
segundo_elemento = [0] * 3

In [23]:
lista_aux = [0] * 3

In [ ]:
matrix_aux = [primer_elemento, segundo_elemento]

In [ ]:
notas = []
for filas in range(numero_alumnos):
    notas.append([0]*numero_asignaturas)

In [29]:
notas = [0] * numero_alumnos
for filas in range(numero_alumnos):
    notas[filas] =  [0] * numero_asignaturas

In [30]:
notas

[[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]]

In [32]:
import numpy as np

In [34]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

Fin explicación de `notas.append([0]*numero_asignaturas)`

In [40]:
def print_Menu():
    print("\n=== MENU ===")
    print("1. Course Average")
    print("2. Student Average")
    print("3. Show grades")
    print("4. Exit")
    opcion = int(input("Introduzca la opción escogida: "))
    return opcion

In [43]:
# Por ahora (antes de programar las funciones), si no escogemos la opión 4 aquí, nos va a dar error porque aun no están programadas
opcion = 0
while opcion != 4:
    opcion = print_Menu()
    if opcion == 1:
        courseAverage()
    elif opcion == 2:
        studentAverage()
    elif opcion == 3:
        studentGrades()
    elif opcion == 4:
        print("Cerrando programa...")
    else:
        print("Escoja una opción válida")


=== MENU ===
1. Course Average
2. Student Average
3. Show grades
4. Exit
Introduzca la opción escogida: 4
Cerrando programa...


Media alumnos

In [ ]:
# Recorro alumnos
    # Inicializo suma a 0
    # suma = nota + suma
    # media = suma/len(notas)
# medias.append(media)

Media asignaturas

In [44]:
notas

[[6.0, 7.0, 8.0], [6.0, 5.0, 6.0], [7.0, 9.0, 9.0], [8.0, 7.0, 6.0]]

In [ ]:
# media_asignaturas = []
# Recorrer for i in range(asignaturas)
    # suma_asinatura = 0
    # Recorrer alumnos 
        # Del primer alumno cojo el primer valor, del segundo cojo el primer valor....
        # suma_asignatura = suma_asignatura + valor[alumno][asignatura] asignatura es la "i" del primer for
        # media_asignatura = suma_asignatura/num_alumnos
    # media_asignaturas.append(media_asignatura)

Para no meternos en el lío de recorrer columnas, utilizamos numpy

In [45]:
import numpy as np

Explicación adicional funciones

In [49]:
def funcion_aux(param1=2, param2=4):
    print(param1)
    print(param2)
    

In [51]:
funcion_aux()

2
4


In [52]:
funcion_aux(2,5)

2
5


In [55]:
funcion_aux(param2=5)

2
5


Fin explicación adicional funciones

In [56]:
notas

[[6.0, 7.0, 8.0], [6.0, 5.0, 6.0], [7.0, 9.0, 9.0], [8.0, 7.0, 6.0]]

In [63]:
notas_numpy = np.array(notas)
notas_numpy

array([[6., 7., 8.],
       [6., 5., 6.],
       [7., 9., 9.],
       [8., 7., 6.]])

In [64]:
media_asignaturas = notas_numpy.mean(0)
media_alumnos = notas_numpy.mean(1)

In [65]:
media_asignaturas

array([6.75, 7.  , 7.25])

In [70]:
media_alumnos

array([7.        , 5.66666667, 8.33333333, 7.        ])

# Program 1 - Ahora con diccionarios

Explicación diccionarios

In [76]:
alumnos = dict(alumno1=[1,2,3], alumno2=[6,7,8])

In [77]:
alumnos

{'alumno1': [1, 2, 3], 'alumno2': [6, 7, 8]}

In [78]:
alumnos = {"alumno1":[1,2,3], "alumno2":[6,7,8]}

In [79]:
alumnos

{'alumno1': [1, 2, 3], 'alumno2': [6, 7, 8]}

In [80]:
alumnos["alumno1"]

[1, 2, 3]

In [81]:
alumnos.keys()

dict_keys(['alumno1', 'alumno2'])

In [85]:
for nombre in alumnos.keys():
    print(nombre)

alumno1
alumno2


In [86]:
datos_personales= dict(nombre = " ", edad = 0, calle = " ")

In [87]:
datos_pedro = dict(nombre = "Pedro", edad = 20, calle = "A")
datos_juan = dict(nombre = "Juen", edad = 18, calle = " ")

In [89]:
num_personas = 2
lista_datos_personas = []
for i in range(num_personas):
    nombre = input("Nombre: ")
    edad = int(input("Edad"))
    calle = input("Calle")
    nuevo_dict = dict(nombre = nombre, edad = edad, calle = calle)
    lista_datos_personas.append(nuevo_dict)

Nombre: Pedro
Edad20
CalleA
Nombre: Felipe
Edad30
Calle


In [90]:
print(lista_datos_personas)

[{'nombre': 'Pedro', 'edad': 20, 'calle': 'A'}, {'nombre': 'Felipe', 'edad': 30, 'calle': ''}]


In [93]:
for diccionario in lista_datos_personas:
    print(diccionario['nombre'])

Pedro
Felipe


In [94]:
datos_nico = dict(nombre = "Nico", edad = 22, calle = "A")

In [96]:
datos_nico['calle']

'A'

Fin explicación diccionarios

In [97]:
numero_alumnos = int(input("Introduzca el número de alumnos: "))

alumnos = []
for i in range(numero_alumnos):
    alumno = input("Introduzca el nombres del alumno: ")
    alumnos.append(alumno)

Introduzca el número de alumnos: 3
Introduzca el nombres del alumno: Felipe
Introduzca el nombres del alumno: Nico
Introduzca el nombres del alumno: Cris


In [99]:
a = dict(R = 4, Python = 8, Contabilidad = 7.5)

In [100]:
a["Estadistica"] = 6

In [101]:
a

{'R': 4, 'Python': 8, 'Contabilidad': 7.5, 'Estadistica': 6}

In [102]:
lista_asignaturas = ["R", "Python", "Contabilidad"]

In [107]:
lista_datos = []
numero_alumnos = 2
for i in range(numero_alumnos):
    notas = dict()
    notas['nombre']= input("Alumno: ")
    notas[lista_asignaturas[0]] = float(input("nota R "))
    notas[lista_asignaturas[1]] = float(input("nota python "))
    notas[lista_asignaturas[2]] = float(input("nota cont "))
    lista_datos.append(notas)

Alumno: Nico
nota R 5
nota python 6
nota cont 3
Alumno: Pedro
nota R 6
nota python 8
nota cont 9


In [108]:
lista_datos

[{'nombre': 'Nico', 'R': 5.0, 'Python': 6.0, 'Contabilidad': 3.0},
 {'nombre': 'Pedro', 'R': 6.0, 'Python': 8.0, 'Contabilidad': 9.0}]

[     ]    [      ]     [     ]


[     ]
    Nombre
    R
    Python
    Contabilidad


In [111]:
for elemento in lista_datos:
    print(elemento['nombre'])
    print(elemento['R'])

Nico
5.0
Pedro
6.0


In [114]:
lista_datos[0]['R'] = 10

In [116]:
lista_datos

[{'nombre': 'Nico', 'R': 10, 'Python': 6.0, 'Contabilidad': 3.0},
 {'nombre': 'Pedro', 'R': 6.0, 'Python': 8.0, 'Contabilidad': 9.0}]

Manera 2

In [ ]:
[nombre1   nombre2   nombre3]

nombre1
    R
    Python
    Contabilidad

nombre2
    R
    Pyhon
    Contabilidad
    

In [ ]:
# lista_datos["Nico"]["R"] = 7

In [121]:
lista_datos_nueva = dict(Nico = dict(), Pedro = dict(), Juan = dict())

In [122]:
lista_datos_nueva

{'Nico': {}, 'Pedro': {}, 'Juan': {}}

In [123]:
lista_datos_nueva['Nico']['R'] = 3

In [124]:
lista_datos_nueva

{'Nico': {'R': 3}, 'Pedro': {}, 'Juan': {}}

In [125]:
lista_datos_nueva["María"] = dict(R=4)

In [126]:
lista_datos_nueva

{'Nico': {'R': 3}, 'Pedro': {}, 'Juan': {}, 'María': {'R': 4}}

In [127]:
lista_datos_nueva["María"] = 4

In [128]:
lista_datos_nueva

{'Nico': {'R': 3}, 'Pedro': {}, 'Juan': {}, 'María': 4}

In [133]:
lista_datos_nueva["María"] = dict(R=4)

In [139]:
lista_datos_nueva["María"]["Python"] = 6

In [140]:
lista_datos_nueva

{'Nico': {'R': 3}, 'Pedro': {}, 'Juan': {}, 'María': {'R': 4, 'Python': 6}}

In [143]:
lista_datos_nueva["Cris"] = dict(R = 3, Contabilidad = 7)

In [146]:
lista_datos_nueva.pop("Juan")

{}

In [150]:
lista_datos_nueva.pop("Pedro")

In [151]:
lista_datos_nueva

{'Nico': {'R': 3},
 'María': {'R': 4, 'Python': 6},
 'Cris': {'R': 3, 'Contabilidad': 7}}

In [164]:
lista_datos_nueva["María"]

{'R': 4, 'Python': 6}

In [166]:
for nombre in lista_datos_nueva:
    print(lista_datos_nueva[nombre])

{'R': 3}
{'R': 4, 'Python': 6}
{'R': 3, 'Contabilidad': 7}


In [176]:
for nombre in lista_datos_nueva:
    print(nombre)
    for asignatura in lista_datos_nueva[nombre]:
        print(asignatura)
        print(lista_datos_nueva[nombre][asignatura])

Nico
R
3
María
R
4
Python
6
Cris
R
3
Contabilidad
7


In [183]:
for nombre in lista_datos_nueva:
    print(nombre)
    print(lista_datos_nueva[nombre])
    for asignatura in lista_datos_nueva[nombre]:
        print(asignatura)
        print(lista_datos_nueva[nombre][asignatura])

Nico
{'R': 3}
R
3
María
{'R': 4, 'Python': 6}
R
4
Python
6
Cris
{'R': 3, 'Contabilidad': 7}
R
3
Contabilidad
7
